root: true
ignorePatterns:
  - "/src/src/app/*"
  - "!/src/app/app"
  - "*.js"
  - "*.spec.ts"
parserOptions:
  ecmaVersion: 2022
overrides:
  - files:
      - "*.ts"
    env:
      browser: true
    parserOptions:
      project:
        - "tsconfig.(app|spec).json"
    extends:
      - "./node_modules/gts/"
      - "eslint:recommended"
      - "plugin:@angular-eslint/all"
      - "plugin:@angular-eslint/template/process-inline-templates"
    plugins:
      - "prefer-arrow"
      - "unused-imports"
    rules:
      eqeqeq: "off"
      grouped-accessor-pairs:
        - "error"
        - "setBeforeGet"
      node/no-unsupported-features/node-builtins:
        - "error"
        - version: ">=14.20.0"
          ignores: []
      no-this-before-super: "error"
      no-unused-vars: "off"
      prefer-arrow/prefer-arrow-functions: "error"
      prefer-template: "error"
      prettier/prettier: "off"
      "@angular-eslint/component-max-inline-declarations":
        - "error"
        - animations: 40
          styles: 10
          template: 10
      "@typescript-eslint/explicit-function-return-type":
        - "error"
        - allowExpressions: true
      "@angular-eslint/no-forward-ref": "off"
      "@angular-eslint/no-pipe-impure": "off"
      "@angular-eslint/no-output-native": "off"
      "@angular-eslint/no-output-on-prefix": "off"
      "@angular-eslint/prefer-on-push-component-change-detection": "off"
      "@angular-eslint/sort-ngmodule-metadata-arrays": "off"
      "@angular-eslint/use-component-view-encapsulation": "off"
      "@angular-eslint/use-injectable-provided-in": "off"
      "@typescript-eslint/member-ordering":
        - "error"
        - default:
            - "public-decorated-field"
            - "public-decorated-method"
            - "protected-decorated-field"
            - "private-decorated-field"
            - "public-abstract-field"
            - "public-static-field"
            - "public-instance-field"
            - "protected-abstract-field"
            - "protected-static-field"
            - "protected-instance-field"
            - "private-static-field"
            - "private-instance-field"
            - "constructor"
            - "public-abstract-method"
            - "public-static-method"
            - "public-instance-method"
            - "public-method"
            - "protected-abstract-method"
            - "protected-decorated-method"
            - "protected-instance-method"
            - "protected-method"
            - "protected-static-method"
            - "private-instance-method"
            - "private-method"
            - "private-static-method"
      "@typescript-eslint/no-explicit-any": "off"
      "@typescript-eslint/no-floating-promises": "off"
      "@typescript-eslint/no-unsafe-assignment": "off"
      "@typescript-eslint/no-unsafe-call": "off"
      "@typescript-eslint/no-unsafe-member-access": "off"
      "@typescript-eslint/prefer-for-of": "error"
      "@typescript-eslint/prefer-readonly": "error"
      "@typescript-eslint/unbound-method":
        - "error"
        - ignoreStatic: true
      "unused-imports/no-unused-imports-ts": "error"
      "unused-imports/no-unused-vars":
        - "error"
        - vars: "all"
          varsIgnorePattern: "^_"
          args: "after-used"
          argsIgnorePattern: "^_"
      "@typescript-eslint/no-empty-function":
        - "error"
        - allow:
            - "arrowFunctions"
            - "methods"
      "@typescript-eslint/no-unused-vars": "off"
  - files:
      - "*.html"
    excludedFiles:
      - "*inline-template-*.component.html"
    extends:
      - "plugin:@angular-eslint/template/recommended"
    plugins:
      - "@angular-eslint/template"
    rules:
      "@angular-eslint/template/conditional-complexity":
        - "error"
        - maxComplexity: 16
      "@angular-eslint/template/cyclomatic-complexity":
        - "error"
        - maxComplexity: 71
      "@angular-eslint/template/eqeqeq": "off"
      "@angular-eslint/template/no-any": "error"
      "@angular-eslint/template/use-track-by-function": "warn"
