nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:8000/
              description: API over HTTP
            - url: https://api.grammerjourney.lukas-boecker.de/
              description: API over HTTPS
        info:
            title: Grammerjourney API
            description: This is the API documentation for the Grammerjourney API.
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns:
            - ^/api(?!/doc|doc.json$) # Accepts routes under /api except /api/doc
        user:
            path_patterns:
                - ^/api/register
                - ^/api/login