version: '3.8'
networks:
  grammerjourney:

services:
  nginx:
    container_name: grammerjourney_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../backend:/var/www/grammerjourney
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/dist:/var/www/grammerjourney/frontend
    depends_on:
      - php
      - database
    networks:
      - grammerjourney

  php:
    container_name: grammerjourney_php
    build: ./php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '9000:9000'
    volumes:
      - ../backend:/var/www/grammerjourney
    depends_on:
      - database
    networks:
      - grammerjourney

  database:
    container_name: grammerjourney_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - grammerjourney
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: grammerjourney
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - ../backend/mysql:/var/lib/mysql

  frontend:
    container_name: grammerjourney_frontend
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ../frontend/src:/usr/share/nginx/html
    networks:
      - grammerjourney
