version: '3.8'
networks:
  grammerjourney:

services:
  backend_nginx:
    container_name: grammerjourney_backend
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../backend:/var/www/grammerjourney
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - grammerjourney

  frontend_nginx:
    container_name: grammerjourney_frontend
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ../frontend:/var/www/grammerjourney
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - grammerjourney

  php:
    container_name: grammerjourney_php
    build:
      context: ./php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '9000:9000'
    volumes:
      - ../backend:/var/www/grammerjourney
    depends_on:
      - database
    networks:
      - grammerjourney

  database:
    container_name: grammerjourney_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - grammerjourney
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: grammerjourney
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
