name: Unit

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: composer

      - name: Install dependencies
        run: |
          cd backend
          composer install

      - name: Run PHPUnit tests
        run: |
          cd backend
          vendor/bin/phpunit