name: Deploy grammerjourney

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Deploy main site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /var/www/html/grammerjourney.lukas-boecker.de && git pull origin main --no-rebase --autostash
            cp -R /var/www/html/grammerjourney.lukas-boecker.de/frontend/ /root/grammerjourney.lukas-boecker.de/html/
            cp -R /var/www/html/grammerjourney.lukas-boecker.de/backend/ /root/grammerjourney.lukas-boecker.de/html/
