name: Deploy grammerjourney

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      #- name: Install Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: '16.x'

      #- name: Install npm Dependencies
      #  run: npm install

      #- name: Run Build Task
      #  run: npm run build --if-present

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: 22
          ARGS: "-rlgoDzvc -i"
          SSH_CMD_ARGS: "-o StrictHostKeyChecking=no"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
