name: Deploy grammerjourney
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Deploy main site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 20.1.0
            cd /var/www/html/grammerjourney.lukas-boecker.de && git pull origin main --no-rebase --autostash
            cd /var/www/html/grammerjourney.lukas-boecker.de && git pull --no-rebase --autostash
            cd /var/www/html/grammerjourney.lukas-boecker.de/frontend && npm install && npm run build --aot --build-optimizer --common-chunk --vendor-chunk --optimization --progress --configuration=production
            cp -R /var/www/html/grammerjourney.lukas-boecker.de/frontend/dist /root/grammerjourney.lukas-boecker.de/html/
            cp -R /var/www/html/grammerjourney.lukas-boecker.de/backend/ /root/api-grammerjourney.lukas-boecker.de/html/
            
