name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: deploy main site
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/grammerjourney.lukas-boecker.de && git pull --no-rebase --autostash
            cp -R /var/www/html/grammerjourney.lukas-boecker.de/frontend/ /root/grammerjourney.lukas-boecker.de/html/
            cp -R /var/www/html/grammerjourney.lukas-boecker.de/backend/ /root/api.lukas-boecker.de/html/
